export const CREATE_ACCOUNT_PENDING = "CREATE_ACCOUNT_PENDING";
export const CREATE_ACCOUNT_COMPLETED = "CREATE_ACCOUNT_COMPLETED";
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
